-- MySQL Script generated by MySQL Workbench
-- Tue Sep 26 17:03:03 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema e22013117_db2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema e22013117_db2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `e22013117_db2` DEFAULT CHARACTER SET utf8 ;
USE `e22013117_db2` ;

-- -----------------------------------------------------
-- Table `e22013117_db2`.`T_COMPTE_CPT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e22013117_db2`.`T_COMPTE_CPT` (
  `CPT_id` INT NOT NULL AUTO_INCREMENT,
  `CPT_pseudo` VARCHAR(45) CHARACTER SET 'utf8mb4' NOT NULL,
  `CPT_mdp` CHAR(64) NOT NULL,
  PRIMARY KEY (`CPT_id`),
  UNIQUE INDEX `CPT_pseudo_UNIQUE` (`CPT_pseudo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22013117_db2`.`T_PROFIL_PRO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e22013117_db2`.`T_PROFIL_PRO` (
  `PRO_nom` VARCHAR(80) NOT NULL,
  `PRO_prenom` VARCHAR(80) NOT NULL,
  `PRO_role` CHAR(1) NOT NULL,
  `PRO_validite` CHAR(1) NOT NULL,
  `CPT_id` INT NOT NULL,
  PRIMARY KEY (`CPT_id`),
  UNIQUE INDEX `CPT_id_UNIQUE` (`CPT_id` ASC) VISIBLE,
  CONSTRAINT `fk_T_PROFIL_PRO_T_COMPTE_CPT`
    FOREIGN KEY (`CPT_id`)
    REFERENCES `e22013117_db2`.`T_COMPTE_CPT` (`CPT_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22013117_db2`.`T_ACTUALITE_ACT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e22013117_db2`.`T_ACTUALITE_ACT` (
  `ACT_id` INT NOT NULL AUTO_INCREMENT,
  `ACT_intitule` VARCHAR(300) NOT NULL,
  `ACT_description` VARCHAR(300) NOT NULL,
  `ACT_date` DATE NOT NULL,
  `CPT_id` INT NOT NULL,
  PRIMARY KEY (`ACT_id`),
  INDEX `fk_T_ACTUALITE_ACT_T_COMPTE_CPT1_idx` (`CPT_id` ASC) VISIBLE,
  CONSTRAINT `fk_T_ACTUALITE_ACT_T_COMPTE_CPT1`
    FOREIGN KEY (`CPT_id`)
    REFERENCES `e22013117_db2`.`T_COMPTE_CPT` (`CPT_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22013117_db2`.`T_SCENARIO_SCE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e22013117_db2`.`T_SCENARIO_SCE` (
  `SCE_id` INT NOT NULL AUTO_INCREMENT,
  `SCE_intituler` VARCHAR(300) NOT NULL,
  `SCE_code` CHAR(10) CHARACTER SET 'utf8mb4' NOT NULL,
  `SCE_description` VARCHAR(300) NOT NULL,
  `SCE_activite` CHAR(1) NOT NULL,
  `CPT_id` INT NULL,
  `SCE_ressource` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`SCE_id`),
  INDEX `fk_T_SCENARIO_SCE_T_COMPTE_CPT1_idx` (`CPT_id` ASC) VISIBLE,
  CONSTRAINT `fk_T_SCENARIO_SCE_T_COMPTE_CPT1`
    FOREIGN KEY (`CPT_id`)
    REFERENCES `e22013117_db2`.`T_COMPTE_CPT` (`CPT_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22013117_db2`.`T_RESSOURCE_RSC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e22013117_db2`.`T_RESSOURCE_RSC` (
  `RSC_id` INT NOT NULL AUTO_INCREMENT,
  `RSC_chemin` VARCHAR(300) NOT NULL,
  `RSC_type` CHAR(1) NOT NULL,
  PRIMARY KEY (`RSC_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22013117_db2`.`T_ETAPE_ETP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e22013117_db2`.`T_ETAPE_ETP` (
  `ETP_id` INT NOT NULL AUTO_INCREMENT,
  `ETP_intituler` VARCHAR(300) NOT NULL,
  `ETP_code` CHAR(8) CHARACTER SET 'utf8mb4' NOT NULL,
  `ETP_description` VARCHAR(300) NOT NULL,
  `ETP_reponse` VARCHAR(300) NOT NULL,
  `ETP_ordre` INT NOT NULL,
  `SCE_id` INT NOT NULL,
  `RSC_id` INT NOT NULL,
  PRIMARY KEY (`ETP_id`),
  INDEX `fk_T_ETAPE_ETP_T_SCENARIO_SCE1_idx` (`SCE_id` ASC) VISIBLE,
  INDEX `fk_T_ETAPE_ETP_T_RESSOURCE_RSC1_idx` (`RSC_id` ASC) VISIBLE,
  CONSTRAINT `fk_T_ETAPE_ETP_T_SCENARIO_SCE1`
    FOREIGN KEY (`SCE_id`)
    REFERENCES `e22013117_db2`.`T_SCENARIO_SCE` (`SCE_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_ETAPE_ETP_T_RESSOURCE_RSC1`
    FOREIGN KEY (`RSC_id`)
    REFERENCES `e22013117_db2`.`T_RESSOURCE_RSC` (`RSC_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22013117_db2`.`T_PARTICIPANT_PTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e22013117_db2`.`T_PARTICIPANT_PTS` (
  `PTS_id` INT NOT NULL AUTO_INCREMENT,
  `PTS_mail` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`PTS_id`),
  UNIQUE INDEX `PTS_mail_UNIQUE` (`PTS_mail` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22013117_db2`.`T_INDICE_IDE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e22013117_db2`.`T_INDICE_IDE` (
  `IDE_id` INT NOT NULL AUTO_INCREMENT,
  `IDE_lien` VARCHAR(300) NOT NULL,
  `IDE_description` VARCHAR(300) NOT NULL,
  `IDE_niveau` INT NOT NULL,
  `ETP_id` INT NOT NULL,
  PRIMARY KEY (`IDE_id`),
  INDEX `fk_T_INDICE_IDE_T_ETAPE_ETP1_idx` (`ETP_id` ASC) VISIBLE,
  CONSTRAINT `fk_T_INDICE_IDE_T_ETAPE_ETP1`
    FOREIGN KEY (`ETP_id`)
    REFERENCES `e22013117_db2`.`T_ETAPE_ETP` (`ETP_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22013117_db2`.`T_RESULTAT_RLT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e22013117_db2`.`T_RESULTAT_RLT` (
  `RLT_premieredate` DATE NOT NULL,
  `RLT_dernieredate` DATE NOT NULL,
  `RLT_niveau` INT NOT NULL,
  `SCE_id` INT NOT NULL,
  `PTS_id` INT NOT NULL,
  PRIMARY KEY (`SCE_id`, `PTS_id`),
  INDEX `fk_T_RESULTAT_RLT_T_PARTICIPANT_PTS1_idx` (`PTS_id` ASC) VISIBLE,
  CONSTRAINT `fk_T_RESULTAT_RLT_T_SCENARIO_SCE1`
    FOREIGN KEY (`SCE_id`)
    REFERENCES `e22013117_db2`.`T_SCENARIO_SCE` (`SCE_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_RESULTAT_RLT_T_PARTICIPANT_PTS1`
    FOREIGN KEY (`PTS_id`)
    REFERENCES `e22013117_db2`.`T_PARTICIPANT_PTS` (`PTS_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
